# Site settings
title: Durham Atletico
email: info@durhamatletico.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://durhamatletico.com" # the base hostname & protocol for your site
twitter_username: durhamatletico
markdown: kramdown
sass:
  sass_dir: assets/styles/_scss  # default is _sass