title: Durham Atl&eacute;tico
email: info@durhamatletico.com
description: >
  Launched in January 2015, Durham Atlético is a soccer organization dedicated to broadening access to the beautiful game throughout Durham, with a particular focus on the urban core. 
baseurl: "http://durham-atletico.github.io/durhamatletico.com"
url: ""
twitter_username: durhamatletico
markdown: kramdown
sass:
  sass_dir: assets/styles/_scss